### ISSUE TITLE
Include Card Generator as a submodule

### ISSUE THREAD

**Issue by chao-master** [coandco/TSSSF-Frontend#12]
Pros: Everyone knows which version you are using
Makes things friendlier
Avoids having to clone a separate project.

**Comment by coandco** [comment]
Hmm.  While I agree that having some sort of pointer to the version of CardMachine this works with is a laudable idea, I think I'm leaning away from adding it as an actual submodule here.  We've structured this such that it has a separated frontend/backend architecture, so I'm not sure it makes sense to force the user to check out both if they want to tinker with just the frontend.

I'll add a separate issue here to include a reference to the correct repo/branch/version in (say) the README.md, so that people will have an easier time setting it up.  I also like the idea of refactoring the backend to directly use the TSSSFTemplates repo, so I'll add an issue there.
